var GAME_LEVELS = [
  ["  x    !  v  !                                          v                    x  ",
   "  x    !     !                                                               x  ",
   "  x    !     !                                                               x  ",
   "  x    !     !                                                               x  ",
   "  x    !!!v!!!                                          v                    x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                               xPx        x  ",
   "  x                                                xx      xx    xx!xx       x  ",
   "  x                                 o o      xx         v        x!!!x       x  ",
   "  x                                                              xx!xx       x  ",
   "  x                     o          xxxxx                          xvx        x  ",
   "  x                                              xxxxx                       x  ",
   "  x                                       o o                                x  ",
   "  x            xPx      x                                                    x  ",
   "  x           x  x                       xxxxxx         v                  o x  ",
   "  x          x   x      x                                                    x  ",
   "  x  @       x   x          =       = x      =       =          xxxxx   = =  x  ",
   "  xxxxxxxxxxxx   xxxxxxxPxxxxxx   xxxxxxxxxxxxxxxxxPxx     xxxxxxx   xxxxxxPxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["       !  v  !                                                                                                    ",
   "       !     !                                                                                                    ",
   "       !     !                                                                                                    ",
   "       !     !                                                                                                    ",
   "       !!!v!!!                                                                                            o       ",
   "                                                                  xxxxxxx                                    x!x  ",
   "                                                               xxxx     xxxx                                 x!x  ",
   "                                                              xx           xx                                x!x  ",
   "                                                             xx             xx                               x!x  ",
   "                                                             x                                    o   o   o  x!x  ",
   "                                                             x     !   !                                    xx!x  ",
   "                                                             x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                  v          x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx      Px    v                        ",
   "                                                               xxxx!!!!!xxxx       x                              ",
   "                                               P     x            !!!!!!!          x         xxx                  ",
   "                                               x     x                             x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                  x            x     x                             xx        x                    ",
   "                                x   x          xx    x                             x         x                    ",
   "                               xx   xx         x     x      o  o     x   x         x         x                    ",
   "                              xxx   xxx        x     x               x   x         x         x                    ",
   "                                x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "                 xxx            x o x          x     x               x   x   x               x                    ",
   "     @           x x            x   x          x     x               x   x   x     =         x                    ",
   "    xxx          x x            x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x          x x           xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!P!!!x x!!!x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x         x                    ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!x x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["       !     !                                                                                                                         x",
   "       !     !                                                                                                                         x",
   "       !     !                                                                                     v                            xoooooox",
   "       !  v  !                                                                                     v                             xooooox",
   "       !!! !!!                   v                                                                 v                              xoooox",
   "                                 v                                                                 v                               xooox",
   "                                 v                                        v                                                         xxxx",
   "                                                                          v                                                             ",
   "                                                                          v                                                             ",
   "                                                                          v                                                             ",
   "                                                     x                                                                  x               ",
   "                                                                                                                                        ",
   "                                                                                                     x                                  ",
   "                                               P               s                                                                        ",
   "                                                                                                                                       x",
   "                   x                                                                                                                    ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                           x                                            ",
   "                                                                                                                                        ",
   "                              s                                                                                                         ",
   "                                                        x                x                                                              ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "            x                                                                    x                                                      ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                   x                             x                                             s                        ",
   "                                                                                                                              x         ",
   "                                                                                                                                        ",
   "                                                                                                   P                                    ",
   "                                                                                                                                        ",
   "                                  x                                     x                                            x                  ",
   "                                                   P                                                                                    ",
   "            P                                                                                                                           ",
   "                                                                                            x                                           ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                            x                                                                                           ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "                                                                                                                                        ",
   "     @                                                                                                                                  ",
   "             f                                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxx     xxxxxxxxxxxxxx      xxxxxxxxxxxxx   xxxxxxxxxxxxxx         xxxxxxxxxxxx"]
  ["                                                                                                         ",
   "                                                                                                         ",
   "   x                                                                                                x  ",
   "   x                                                                                                x  ",
   "   x                                                                                                x  ",
   "   x                                                                                                x  ",
   "   x                                                                                                x  ",
   "   x!     !  !!!!  !   !    !       ! !!! !     !                                                 x  ",
   "   x !   !  !    ! !   !    !   !   !  !  !!    !                                                 x  ",
   "   x  ! !   !    ! !   !    !   !   !  !  ! !   !                                                 x  ",
   "   x   !    !    ! !   !    !   !   !  !  !  !  !                                                 x  ",
   "   x   !    !    ! !   !    !  ! !  !  !  !   ! !                                                 x  ",
   "   x   !    !    ! !   !    ! !   ! !  !  !    !!                                                 x  ",
   "   x   !     !!!!   !!!      !     !  !!! !     !                                                 x  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                         "]]

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
